export const GET_CITIZEN_ID = 'GET_CITIZEN_ID';
export const GET_LOGIN_ADMIN = 'GET_LOGIN_ADMIN';
export const GET_LOGIN_CITIZEN = 'GET_LOGIN_CITIZEN';
export const LOGOUT = "LOGOUT";
export const GET_LIST_CITIZEN = 'GET_LIST_CITIZEN';
export const GET_LIST_ADMIN = 'GET_LIST_ADMIN';